[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.30"
solc = "0.8.30"

[profile.default.zksync]
enabled = true
codegen = "evmla"

[rpc_endpoints]
local = "${ERA_TEST_NODE_RPC_URL}"